# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KFG3i0aCrxfRVATzEjPeLHHFT3O_Luxr
"""

def tashxis(belgi):
  if belgi == "istima":
    return "Parasetamol iching"
  elif belgi == "bosh og'riq":
    return "Trimol iching"
  elif belgi== "Tish og'riq":
    return "Quepen iching"
  elif belgi== "rematizm":
    return "sustavit"
  elif belgi== "alergiya":
    return "lorotadine"
  elif belgi== "yo'tal":
    return "ambroxol"
  elif belgi== "aknelar":
    return "benzoyl"
  elif belgi== "tomoq ogrigi":
    return "sitramon"
  else:
    return "shifokorga murojat qiling"
belgi=input("kasallik belgisini kiriting ")
natija=tashxis(belgi)
print(natija)

from google.colab import drive
drive.mount('/content/drive')

def tashxis(belgi):
  if belgi == "dushanba":
    return "kompyutorni tashkil qilish ,kiberxavsizlik asoslari,malumotlar tuzilmasi"
  elif belgi == "seshanba":
    return "suniy intelekt asoslari ,elektronika va sxemalar ,"
  elif belgi== "chorshanba":
    return "kompyutorni tashkil qilish ,suniy intelekt asoslari"
  elif belgi== "payshanba":
    return "kompyutorni tashkil qilish ,kiberxavsizlik asoslari,malumotlar tuzilmasi"
  elif belgi== "juma":
    return "kiberxavsizlik asoslari ,suniy intelekt asoslari ,kompyutorni tashkil qilish"
  else:
    return "shifokorga murojat qiling"
belgi=input("kunni kiriting ")
natija=tashxis(belgi)
print(natija)